### ISSUE TITLE
Replace applications by generic nomenclatures

### ISSUE THREAD

**Issue by Niktux** [lebris/supervisorg#13]
Before : 

``` yaml
applications:
  enabled: true
  regex: "(?P<application>.+)--(?P<processName>.+)"
```

After:

``` yaml
nomemclatures:
  - label: Applications
    value: application@regex
    processName: process@regex
    regex: "(?P<application>.+)--(?P<process>.+)"
  - label: Ponies
    value: Ponies workflow
    processName: process@regex
    regex: "(?P<process>.+)"
```

**Comment by Niktux** [comment]
``` yml
logicalGroups:
    applications:
        defaultView: true
        icon: desktop
        regex: "(?P<groupValue>.+)--(?P<process>.+)"
    animals:
        icon: object-ungroup
        regex: "(.+)--(?P<groupValue>.+)-(?P<process>.+)"
```
